---
title: "Chinese Sister-Cities"
author: "Naimul Chowdhury"
date: "09/27/2020"
output:
  html_document:
    df_print: paged
---

##1. Setup
### options
Set up global options
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70))
knitr::opts_chunk$set(fig.height=4, fig.width=6)
```

### libraries
Load in needed libraries 
```{r, include=FALSE}
library(tidyverse)
library(RColorBrewer)
library(plotly)
```

## 2. File management
### Create variables for directories
```{r file_management, include=FALSE}
project.dir <- "/home/naeem/development/internships/VSFS/CN_AUS_Sisters" #naeem
output.dir <- file.path(project.dir, "output")
data.dir <- file.path(project.dir, "data")
setwd(project.dir)
getwd()

cities <- read_csv(file.path(data.dir, "all_cities_no_gc.csv"))
sisters <- read_csv(file.path(data.dir, "sisters_no_gc.csv"))
sisters <- sisters %>% select(`Australian City`, Aus_LAT, Aus_LNG, `Chinese City`, CN_LAT, CN_LNG)
```

## 3. Playground

### Line Mapping
```{r}
# Add a unique id label to the relationships
sisters$id <- seq_len(nrow(sisters))

#Possibly play with scope to see if we can focus only on the region of interest
geo <- list(
  scope = 'asia', #TODO 1 Find Scope Parameters
  projection = list(type = 'azimuthal equal area'), 
  showland = TRUE, 
  landcolor = toRGB("gray95"), #TODO 2 Set Color
  countrycolor = toRGB("gray80")
)

fig <- plot_geo(locationmode = 'country names', color = I("red"))


# TODO 3 hoverinfo = city name
# Plots the dots
fig <- fig %>% add_markers( 
  data = cities, x = ~lng, y = ~lat, text = ~city_name,
  size = 1, hoverinfo = "city_name", alpha = 1
)



#TODO 6 hoverinfo = "comments"
fig <- fig %>% add_segments(
    data = group_by(sisters, id),
    x = ~Aus_LNG, xend = ~CN_LNG,
    y = ~Aus_LAT, yend = ~CN_LAT,
    alpha = 0.4, size = I(1), hoverinfo = "none"
  )

# Controls most features of the map
fig <- fig %>% layout(
    title = list(text = "Australia-China Sister Cities", 
                 font = list(family = "Droid Sans", size = 32), 
                 y = 1, showlegend = TRUE),
    geo = list(
      resolution = 100,
      showland = TRUE,
      showlakes = TRUE,
      showocean = TRUE,
      showcountries = TRUE,
      landcolor = toRGB("grey80"),
      countrycolor = "#444",
      bgcolor = "#fff",
      lakecolor = toRGB("#0077BE"),
      oceancolor = toRGB("#3399FF"),
      projection = list(type = "equirectangular"),
      coastlinewidth = 2,
      lataxis = list(
        range = c(-50, 70),
        showgrid = TRUE,
        tickmode = "linear",
        dtick = 10
        ),
      lonaxis = list(
        range = c(40, 170),
        showgrid = TRUE,
        tickmode = "linear",
        dtick = 20
      )
    )
    , showlegend = FALSE, height = 1024, width = 768
)

fig

```


